package oracle.model.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 23 15:29:20 CDT 2013
// ---------------------------------------------------------------------
public class DepartmentsRowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = {
        { "oracle.model.Departments.departmentId_LABEL", "" }, { "oracle.model.Departments.departmentName_LABEL", "" },
        { "oracle.model.Departments.locationId_LABEL", "" }
    };

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsRowImplMsgBundle() {
    }

    /**
     * @return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}

